/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Category;
import bean.News;
import com.hexidec.ekit.Ekit;
import com.hexidec.ekit.EkitCore;
import controller.ControllerCat;
import controller.ControllerNew;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import model.ModelNews;
import render.RenderComboBoxModelCat;

/**
 *
 * @author vuongluis
 */
public class pnNew extends javax.swing.JPanel {

    /**
     * Creates new form pnDemo
     */
    private ControllerNew controller;
    private ControllerCat controllerCat;
    private String imageAvatar = "imagehere.png";
    private Category objCat;
    private EkitCore ekitCore = new EkitCore();

    
    public pnNew() {
        initComponents();
        
        controller = new ControllerNew(tbMain);
        controllerCat = new ControllerCat(tbMain);
        
        controller.loadTable();
        controllerCat.loadCategory(cbDanhMuc, false, null);
        controllerCat.loadCategory(cbDanhMucF, true, null);
        
        btnEkitEditor.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                btnEkitEditor.setIcon(new ImageIcon(getClass().getResource("/images/edit-icon.gif")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnEkitEditor.setIcon(new ImageIcon(getClass().getResource("/images/text-editor.png")));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jSplitPaneNew = new javax.swing.JSplitPane();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEkitEditor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        spDate = new javax.swing.JSpinner();
        cbDanhMuc = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        lbAvatar = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        TopRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnNhapLaiF = new javax.swing.JButton();
        btnThoatF = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNameF = new javax.swing.JTextField();
        tfIDF = new javax.swing.JTextField();
        cbDanhMucF = new javax.swing.JComboBox();
        spDateFY = new javax.swing.JSpinner();
        spDateFX = new javax.swing.JSpinner();
        btnDate = new javax.swing.JButton();
        BottomRight = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(1129, 400));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(242, 242, 242));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jSplitPaneNew.setBackground(new java.awt.Color(242, 242, 242));
        jSplitPaneNew.setForeground(new java.awt.Color(204, 102, 0));
        jSplitPaneNew.setOneTouchExpandable(true);

        Left.setBackground(new java.awt.Color(242, 242, 242));
        Left.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 67, 74))); // NOI18N
        Left.setPreferredSize(new java.awt.Dimension(440, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("ID tin:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Tên tin:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Hình ảnh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Mô tả:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Ngày đăng:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Danh mục:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Chi tiết:");

        btnEkitEditor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnEkitEditor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text-editor.png"))); // NOI18N
        btnEkitEditor.setText("Soạn");
        btnEkitEditor.setContentAreaFilled(false);
        btnEkitEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkitEditorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        btThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jPanel1.add(btThem);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        btnNhapLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhapLai);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        tfID.setEditable(false);
        tfID.setPreferredSize(new java.awt.Dimension(59, 28));

        tfName.setPreferredSize(new java.awt.Dimension(59, 28));

        tfDescription.setColumns(20);
        tfDescription.setLineWrap(true);
        tfDescription.setRows(5);
        tfDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tfDescription);

        btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.setPreferredSize(new java.awt.Dimension(81, 28));
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        spDate.setModel(new javax.swing.SpinnerDateModel());
        spDate.setEditor(new javax.swing.JSpinner.DateEditor(spDate, "dd/MM/yyyy HH:mm:ss"));
        spDate.setPreferredSize(new java.awt.Dimension(29, 28));

        cbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDanhMuc.setMinimumSize(new java.awt.Dimension(56, 28));
        cbDanhMuc.setPreferredSize(new java.awt.Dimension(56, 28));

        txtDetail.setColumns(20);
        txtDetail.setLineWrap(true);
        txtDetail.setRows(5);
        txtDetail.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDetail);

        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagehere.png"))); // NOI18N

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEkitEditor))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(LeftLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(spDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LeftLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEkitEditor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPaneNew.setLeftComponent(Left);

        Right.setBackground(new java.awt.Color(242, 242, 242));
        Right.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh Sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 16), new java.awt.Color(0, 67, 74))); // NOI18N
        Right.setLayout(new java.awt.BorderLayout());

        TopRight.setBackground(new java.awt.Color(242, 242, 242));
        TopRight.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 10, 10, new java.awt.Color(242, 242, 242)));
        TopRight.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(242, 242, 242)));
        jPanel3.setForeground(new java.awt.Color(242, 242, 242));
        jPanel3.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimKiem);

        btnNhapLaiF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhapLaiF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnNhapLaiF.setText("Nhập lại");
        btnNhapLaiF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiFActionPerformed(evt);
            }
        });
        jPanel3.add(btnNhapLaiF);

        btnThoatF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoatF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btnThoatF.setText("Tắt");
        btnThoatF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatFActionPerformed(evt);
            }
        });
        jPanel3.add(btnThoatF);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("ID:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Tên:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Danh mục:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Ngày đăng:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Đến:");

        tfNameF.setPreferredSize(new java.awt.Dimension(59, 28));

        tfIDF.setPreferredSize(new java.awt.Dimension(59, 28));

        cbDanhMucF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDanhMucF.setPreferredSize(new java.awt.Dimension(56, 28));

        spDateFY.setModel(new javax.swing.SpinnerDateModel());
        spDateFY.setEditor(new javax.swing.JSpinner.DateEditor(spDateFY, "dd/MM/yyyy HH:mm:ss"));
        spDateFY.setPreferredSize(new java.awt.Dimension(29, 28));

        spDateFX.setModel(new javax.swing.SpinnerDateModel());
        spDateFX.setEditor(new javax.swing.JSpinner.DateEditor(spDateFX, "dd/MM/yyyy HH:mm:ss"));
        spDateFX.setPreferredSize(new java.awt.Dimension(29, 28));

        btnDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDate.setForeground(java.awt.Color.green);
        btnDate.setText("V");
        btnDate.setPreferredSize(new java.awt.Dimension(73, 28));
        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spDateFX, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spDateFY, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNameF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbDanhMucF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tfNameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbDanhMucF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(spDateFY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spDateFX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        TopRight.add(jPanel2, java.awt.BorderLayout.CENTER);

        Right.add(TopRight, java.awt.BorderLayout.PAGE_START);

        BottomRight.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 10, 10, new java.awt.Color(242, 242, 242)));
        BottomRight.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 350));
        jPanel4.setLayout(new java.awt.BorderLayout());

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMainKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tbMain);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        BottomRight.add(jPanel4, java.awt.BorderLayout.CENTER);

        Right.add(BottomRight, java.awt.BorderLayout.CENTER);

        jSplitPaneNew.setRightComponent(Right);

        jPanel5.add(jSplitPaneNew, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        // TODO add your handling code here:
        this.setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void tbMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyReleased
        // TODO add your handling code here:
        this.setForm();
    }//GEN-LAST:event_tbMainKeyReleased

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("C:\\Users\\vuongluis\\Pictures\\");
        int result = chooser.showDialog(null, "Upload Ảnh");
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                File file = chooser.getSelectedFile();
                // lấy tên hình ảnh
                String fileName = file.getName();
                // validate or filter file extension
                
                // file.getAbsoluteFile();
                Path source = Paths.get( file.getAbsolutePath());
                Path target = Paths.get("files/"+fileName);
                /** If the picture is exist so this picture replace that picture. **/
                Files.copy(source,target ,StandardCopyOption.REPLACE_EXISTING );
                Image image =new ImageIcon("files/"+fileName).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                lbAvatar.setIcon(new ImageIcon(image));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
       String name = tfName.getText();
       String preview_text = tfDescription.getText();
       String picture = imageAvatar;
       Category objCat = new RenderComboBoxModelCat(false, null).getElementAt(cbDanhMuc.getSelectedIndex());
       Date utilDate = (Date) spDate.getValue();
       java.sql.Timestamp date_create = new java.sql.Timestamp(utilDate.getTime());
       String detail_text = txtDetail.getText();
//       System.out.println(""
//                + ":"+name
//                + ":"+preview_text
//                + ":"+picture
//                + ":"+objCat.getName()
//                + ":"+date_create
//                + ":"+detail_text
//                + ":"+objCat.getId()
//                + "");
       News item = new News(0, name,preview_text, detail_text, picture, date_create, objCat.getId(), objCat.getName());
       if(isValid(item,"add")){
          int result = controller.addItem(item);
          if(result > 0){
              JOptionPane.showMessageDialog(new pnCat(), "Thêm mới thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
          }else{
              JOptionPane.showMessageDialog(new pnCat(), "Thêm mới thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
          } 
       }
    }//GEN-LAST:event_btThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        tbMain.setRowSorter(sorter);
        
        ArrayList<RowFilter<AbstractTableModel,Object>> alFilter = new ArrayList<>();
        
        String id = tfIDF.getText();
        RowFilter<AbstractTableModel,Object> filterID = RowFilter.regexFilter(id, 0);
        
        String name = tfNameF.getText();
        RowFilter<AbstractTableModel,Object> filterName = RowFilter.regexFilter(name, 1);
        
        alFilter.add(filterID);
        alFilter.add(filterName);
        
        objCat = (Category) cbDanhMucF.getSelectedItem();
        if(objCat.getId() != 0){
            RowFilter<AbstractTableModel,Object> filterCat = new RowFilter<AbstractTableModel, Object>() {
                @Override
                public boolean include(RowFilter.Entry<? extends AbstractTableModel, ? extends Object> entry) {
                    // Cateogry objFindCat = (Category)entry.getValue(4) 
                    String nameCat = (String) entry.getValue(4);
                    return objCat.getName().equals(nameCat);
                }
            };
            alFilter.add(filterCat);
        }

        // tìm ngày
        if(!"X".equals(btnDate.getText())){
            Date dateFrom = (Date) spDateFX.getValue();
            RowFilter<AbstractTableModel,Object> filterDateFrom = RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, dateFrom, 3);
            alFilter.add(filterDateFrom);

            Date dateTo = (Date) spDateFY.getValue();
            RowFilter<AbstractTableModel,Object> filterDateTo = RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, dateTo, 3);
            alFilter.add(filterDateTo);
        }
        RowFilter<AbstractTableModel,Object> filterAnd = RowFilter.andFilter(alFilter);
        sorter.setRowFilter(filterAnd);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            // When i delete new from table, way to good to delete get id from textfield
            int id = Integer.parseInt(tfID.getText());
            if(controller.delItem(id,row)>0){
                JOptionPane.showMessageDialog(new pnCat(), "Xóa tin tức thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(new pnCat(), "Xóa tin tức thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(new pnCat(), "Chưa chọn dòng để xóa","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        this.resetForm();
        
        tfName.requestFocus();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tbMain.getSelectedRow();
        if(row >= 0){
            int id = Integer.parseInt(tfID.getText());
            String name = tfName.getText();
            String preview_text = tfDescription.getText();
            String picture = imageAvatar;
            Category objCat = new RenderComboBoxModelCat(false, null).getElementAt(cbDanhMuc.getSelectedIndex());
            Date utilDate = (Date) spDate.getValue();
            java.sql.Timestamp date_create = new java.sql.Timestamp(utilDate.getTime());
            String detail_text = txtDetail.getText();
            News item = new News(id, name, preview_text, detail_text, picture, date_create, objCat.getId(), objCat.getName());
            // Checking field when user update information
            if(isValid(item,"edit")){
                int result = controller.editItem(item,row);
                if(result > 0){
                    JOptionPane.showMessageDialog(new pnCat(), "Cập nhật thành công","Thông báo",JOptionPane.WARNING_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(new pnCat(), "Cập nhật thất bại","Thông báo",JOptionPane.WARNING_MESSAGE);
                } 
             }
        }else{
            JOptionPane.showMessageDialog(new pnCat(), "Chưa chọn dòng để cập nhật","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnNhapLaiFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiFActionPerformed
        // TODO add your handling code here:
        tfIDF.setText("");
        tfNameF.setText("");
        controllerCat.loadCategory(cbDanhMucF, true, null);
        spDateFX.setValue(new Date());
        spDateFY.setValue(new Date());
        
        tfIDF.requestFocus();
    }//GEN-LAST:event_btnNhapLaiFActionPerformed

    private void btnThoatFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatFActionPerformed
        // TODO add your handling code here:
        this.TopRight.setVisible(false);
    }//GEN-LAST:event_btnThoatFActionPerformed

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        // TODO add your handling code here:
        if("V".equals(btnDate.getText())){
            btnDate.setText("X");
            btnDate.setForeground(Color.RED);
            spDateFX.setEnabled(false);
            spDateFY.setEnabled(false);
        }else{
            btnDate.setText("V");
            btnDate.setForeground(Color.GREEN);
            spDateFX.setEnabled(true);
            spDateFY.setEnabled(true);
        }
    }//GEN-LAST:event_btnDateActionPerformed

    private void btnEkitEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkitEditorActionPerformed
        // TODO add your handling code here:
        jScrollPane3.add(ekitCore.getToolBarMain(true));
        jScrollPane3.add(ekitCore.getToolBarFormat(true));
        jScrollPane3.add(ekitCore.getToolBarStyles(true));
        jScrollPane3.add(ekitCore);
    }//GEN-LAST:event_btnEkitEditorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomRight;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel TopRight;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btnDate;
    private javax.swing.JButton btnEkitEditor;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnNhapLaiF;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThoatF;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbDanhMuc;
    private javax.swing.JComboBox cbDanhMucF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPaneNew;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JSpinner spDate;
    private javax.swing.JSpinner spDateFX;
    private javax.swing.JSpinner spDateFY;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIDF;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNameF;
    private javax.swing.JTextArea txtDetail;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        int row = tbMain.getSelectedRow();
        
        int id = (Integer) tbMain.getValueAt(row, 0);
        String name = tbMain.getValueAt(row, 1).toString();
        String description = tbMain.getValueAt(row, 2).toString();
        
        News item = new ModelNews().getItem(id);
        Date date = item.getDate_create();
        String detail = item.getDetail_text();
        
        tfID.setText(id+"");
        tfName.setText(name);
        tfDescription.setText(description);
        spDate.setValue(date);
        txtDetail.setText(detail);

        Image image =new ImageIcon("files/"+item.getPicture()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        lbAvatar.setIcon(new ImageIcon(image));
    }
    
    private void resetForm(){
        tfID.setText("");
        tfName.setText("");
        tfDescription.setText("");
        txtDetail.setText("");
        spDate.setValue(new Date());
    }

    private boolean isValid(News item, String msg) {
        boolean result = true;
        boolean cont = true;
        switch(msg){
            case "add":
                if(item.getName().isEmpty()){
                    result = false;
                    JOptionPane.showConfirmDialog(new pnNew(), "Tên tin tức không được bỏ trống!","Thông báo",JOptionPane.WARNING_MESSAGE);
                    cont = false;
                }
                if(item.getPreview_text().isEmpty() && cont){
                    result = false;
                    JOptionPane.showConfirmDialog(new pnNew(), "Mô tả tin tức không được bỏ trống!","Thông báo",JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "edit":
                if(item.getName().isEmpty()){
                    item.setName(new ModelNews().getItem(item.getId_news()).getName());
                }
                if(item.getDetail_text().isEmpty()){
                    item.setPreview_text(new ModelNews().getItem(item.getId_news()).getPreview_text());
                }
                if(item.getDetail_text().isEmpty()){
                    item.setDetail_text(new ModelNews().getItem(item.getId_news()).getDetail_text());
                }
                if(item.getPicture().isEmpty()){
                    item.setPicture(new ModelNews().getItem(item.getId_news()).getPicture());
                }
                break;
            case "delete":
                break;
        }
        return result;
    }
}
